---
name: Setup Lean
description: Set up the Lean theorem prover for use within GitHub Actions.
author: Julian Berman
inputs:
  default-toolchain:
    description: "A specific toolchain to declare as elan's default toolchain"
    required: false
outputs:
  # Probable TODO:
  #
  # lean-toolchain:
  #   description: "The installed Lean toolchain version."
  # lean-path:
  #   description: "The absolute path to the Lean executable."
  {}
branding:
  icon: "code"
  color: "blue"

runs:
  using: composite

  steps:
    - name: Install elan
      shell: bash
      run: |
        ELAN_ARGS="-y"
        if [ -n "${{ inputs.default-toolchain }}" ]; then
          ELAN_ARGS="$ELAN_ARGS --default-toolchain=${{ inputs.default-toolchain }}"
        fi

        curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- $ELAN_ARGS
        echo "$HOME/.elan/bin/" >> $GITHUB_PATH
