#!/usr/bin/env python3
from pathlib import Path
import sys

*_, default_toolchain_file = sys.argv
path = Path(default_toolchain_file)

if path.name == "lean-toolchain":
    toolchain = path.read_text().strip()
    print(f"default_toolchain_arg=--default-toolchain={toolchain}")
else:
    import tomllib

    leanpkg = tomllib.loads(path.read_text())
    lean3_version = leanpkg["package"]["lean_version"]
    print(f"default_toolchain_arg=--default-toolchain={lean3_version}")
    print("lean3ls=true")
