name: Validate Lean e2e

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: 40 3 * * *
  workflow_dispatch:

defaults:
  run: # because otherwise it's powershell on Windows...
    shell: bash

jobs:
  setup-using-defaults:
    name: Setup ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4

      - name: setup-lean
        id: setup-lean
        uses: ./

      - name: Check lean runs
        run: lean --version

      - name: Check lake runs
        run: lake --version

      - name: Run simple code
        run: |
          printf 'def main : IO Unit := println! "Hello World"\n' lean --run --stdin

  default-toolchain-file:
    name: Setup ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4

      - name: Create a stub lean-toolchain
        run: printf 'leanprover/lean4:v4.3.0-rc2\n' >'${{ runner.temp }}/lean-toolchain'

      - name: setup-lean
        id: setup-lean
        uses: ./
        with:
          default-toolchain-file: ${{ runner.temp }}/lean-toolchain

      - name: Check we got the right version
        run: |
          expected='Lean\ \(version 4.3.0.*Release\)'
          [[ $(lean --version) =~ $expected ]]

  lean3-default-toolchain-file:
    name: Setup ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4

      - name: Create a stub leanpkg.toml
        run: printf '[package]\nlean_version = "leanprover-community/lean:3.51.1"\n' >'${{ runner.temp }}/leanpkg.toml'

      - name: setup-lean
        id: setup-lean
        uses: ./
        with:
          default-toolchain-file: ${{ runner.temp }}/leanpkg.toml

      - run: lean --version
      - name: Check we got the right version
        run: |
          expected='Lean\ \(version 3.51.1.*Release\)'
          [[ $(lean --version) =~ $expected ]]
